version: '3'

services:

  frontend:
    image: react:latest
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_HOST_IP=localhost
      - GRPC_HOST_IP=localhost
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 1G
