version: '3'

services:
          
  grpc-web-react:
    image: grpc-web-react:latest
    container_name: grpc-web-react
    build:
      context: ../envoy
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
      - "9901:9901"
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 1G
  
            
  chat-service:
    image: node:16.17.1
    container_name: chat-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - grpc-web-react
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 1G